### ISSUE TITLE
Using d3-force and d3-quadtree with create-react-app

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [d3/d3-force#138] opened 2019-04-29 21:24 UTC
CRM  strictly requires ES5 modules while d3-force and d3-quadtree are known to have ES6 code. Any suggestions on using these  modules with CRM?

Thanks!
Parul

**Comment by mbostock** [comment] 2019-04-30 16:45
Duplicate of d3/d3-quadtree#23.

**Closed by mbostock** 2019-04-30 16:45 UTC
