### ISSUE TITLE
forceCollision (and others) do not take kindly to being asked to work with a subset of nodes

### ISSUE THREAD

**Issue by JohnArrowwood** [d3/d3-force#74] opened 2016-11-23 02:44 UTC
There is an analysis at http://stackoverflow.com/questions/40671130/make-two-instances-of-d3-forcecollide-play-nice-together.  By overloading the initialize method to filter the incoming node list, you get strange behaviors where the force is not applied correctly between all of the selected nodes.  There appears to be an assumption in the code that every node in the simulation is being acted upon, which is not good encapsulation, and prevents interesting and useful applications of forces that are selective in which nodes they act upon.

**Comment by mbostock** [comment] 2016-11-23 02:46
Duplicate of #72 which was just fixed in today’s release.

**Closed by mbostock** 2016-11-23 02:46 UTC

**Comment by JohnArrowwood** [comment] 2016-11-23 02:51
Outstanding! :)
