### ISSUE TITLE
Native javascript

### ISSUE THREAD

**Issue by Identity-labs** [d3/d3-force#136] opened 2019-04-12 12:08 UTC
Hi,

This code is not a native javascript

https://github.com/d3/d3-force/blob/master/src/link.js#L54

It's possible to change that ?

Thx

**Comment by curran** [comment] 2019-04-12 12:14
More precisely, it's not ES5. It's standard ES6.

Duplicate of *Currently shipping ES6 syntax* #134

**Closed** 2019-04-17 13:58 UTC
